name: Build iOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest-stable'
    - name: Build App
      run: |
        xcodebuild -scheme "My sxpense app" -destination 'generic/platform=iOS' archive -archivePath build/MyExpenseApp.xcarchive
